# Build the project
FROM node:16.17.0-alpine
WORKDIR /SALARY-RECOMMENDATION-FRONTEND
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
COPY . ./
#RUN npm install react-scripts@5.0.1 -g --silent
RUN npm run build
CMD ["npm", "start"]

